apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-executor-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scaling-executor-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scaling-executor-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.8.3
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "0AzC0pEd5IPv"
        - name: MARIADB_DATABASE
          value: "FlaskDB"
        - name: MARIADB_USER
          value: "flaskdb_user"
        - name: MARIADB_PASSWORD
          value: "Km65RIYznGxx"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: scaling-executor-db-service
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: scaling-executor-db
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scaling-executor-clusterrole
rules:
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - replicaset/scale
  - statefulset/scale
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - replicationcontrollers/scale
  verbs:
  - get
  - patch
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaling-executor-serviceaccount
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scaling-executor-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scaling-executor-clusterrole
subjects:
- kind: ServiceAccount
  name: scaling-executor-serviceaccount
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-executor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scaling-executor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scaling-executor
    spec:
      nodeName: martin-testbed-vm1
      serviceAccountName: scaling-executor-serviceaccount
      containers:
      - name: scaling-executor
        image: scaling-executor
        env:
        - name: NAMESPACE
          value: "default"
        - name: MARIADB_DATABASE
          value: "FlaskDB"
        - name: MARIADB_USER
          value: "flaskdb_user"
        - name: MARIADB_PASSWORD
          value: "Km65RIYznGxx"
        - name: MARIADB_URL
          value: "scaling-executor-db-service:3306"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: scaling-executor-service
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: scaling-executor
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30101
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-executor-phpmyadmin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scaling-executor-phpmyadmin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scaling-executor-phpmyadmin
    spec:
      nodeName: martin-testbed-vm1
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        env:
        - name: PMA_HOST
          value: "scaling-executor-db-service:3306"
        - name: PMA_PMADB
          value: "FlaskDB"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: scaling-executor-phpmyadmin-service
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: scaling-executor-phpmyadmin
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100